using Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics;
using System;

namespace CustomALCodeCop
{
    public static class DiagnosticDescriptors
    {
        public static readonly DiagnosticDescriptor Rule0001LocalVariableNaming = new DiagnosticDescriptor(CustomALCodeCopAnalyzers.AnalyzerPrefix + "0001", (LocalizableString)new LocalizableResourceString("Rule0001LocalVariableNamingTitle", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (LocalizableString)new LocalizableResourceString("Rule0001LocalVariableNamingFormat", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), "Design", DiagnosticSeverity.Warning, true, (LocalizableString)new LocalizableResourceString("Rule0001LocalVariableNamingDescription", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (string)null, Array.Empty<string>());
        public static readonly DiagnosticDescriptor Rule0002GlobalVariableNaming = new DiagnosticDescriptor(CustomALCodeCopAnalyzers.AnalyzerPrefix + "0002", (LocalizableString)new LocalizableResourceString("Rule0002GlobalVariableNamingTitle", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (LocalizableString)new LocalizableResourceString("Rule0002GlobalVariableNamingFormat", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), "Design", DiagnosticSeverity.Warning, true, (LocalizableString)new LocalizableResourceString("Rule0002GlobalVariableNamingDescription", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (string)null, Array.Empty<string>());
        public static readonly DiagnosticDescriptor Rule0003ParameterNaming = new DiagnosticDescriptor(CustomALCodeCopAnalyzers.AnalyzerPrefix + "0003", (LocalizableString)new LocalizableResourceString("Rule0003ParameterNamingTitle", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (LocalizableString)new LocalizableResourceString("Rule0003ParameterNamingFormat", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), "Design", DiagnosticSeverity.Warning, true, (LocalizableString)new LocalizableResourceString("Rule0003ParameterNamingDescription", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (string)null, Array.Empty<string>());
        public static readonly DiagnosticDescriptor Rule0004IfStatementBrackets = new DiagnosticDescriptor(CustomALCodeCopAnalyzers.AnalyzerPrefix + "0004", (LocalizableString)new LocalizableResourceString("Rule0004IfStatementBracketsTitle", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (LocalizableString)new LocalizableResourceString("Rule0004IfStatementBracketsFormat", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), "Design", DiagnosticSeverity.Warning, true, (LocalizableString)new LocalizableResourceString("Rule0004IfStatementBracketsDescription", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (string)null, Array.Empty<string>());
        public static readonly DiagnosticDescriptor Rule0005ExitKeywordCapitalization = new DiagnosticDescriptor(CustomALCodeCopAnalyzers.AnalyzerPrefix + "0005", (LocalizableString)new LocalizableResourceString("Rule0005ExitKeywordCapitalizationTitle", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (LocalizableString)new LocalizableResourceString("Rule0005ExitKeywordCapitalizationFormat", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), "Design", DiagnosticSeverity.Warning, true, (LocalizableString)new LocalizableResourceString("Rule0005ExitKeywordCapitalizationDescription", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (string)null, Array.Empty<string>());
        public static readonly DiagnosticDescriptor Rule0006SemicolonAfterProcedureDeclaration = new DiagnosticDescriptor(CustomALCodeCopAnalyzers.AnalyzerPrefix + "0006", (LocalizableString)new LocalizableResourceString("Rule0006SemicolonAfterProcedureDeclarationTitle", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (LocalizableString)new LocalizableResourceString("Rule0006SemicolonAfterProcedureDeclarationFormat", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), "Design", DiagnosticSeverity.Warning, true, (LocalizableString)new LocalizableResourceString("Rule0006SemicolonAfterProcedureDeclarationDescription", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (string)null, Array.Empty<string>());
        public static readonly DiagnosticDescriptor Rule0007InternalProcedure = new DiagnosticDescriptor(CustomALCodeCopAnalyzers.AnalyzerPrefix + "0007", (LocalizableString)new LocalizableResourceString("Rule0007InternalProcedureTitle", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (LocalizableString)new LocalizableResourceString("Rule0007InternalProcedureFormat", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), "Design", DiagnosticSeverity.Warning, true, (LocalizableString)new LocalizableResourceString("Rule0007InternalProcedureDescription", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (string)null, Array.Empty<string>());
        public static readonly DiagnosticDescriptor Rule0008ToolTipPunctuation = new DiagnosticDescriptor(CustomALCodeCopAnalyzers.AnalyzerPrefix + "0008", (LocalizableString)new LocalizableResourceString("Rule0008ToolTipPunctuationTitle", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (LocalizableString)new LocalizableResourceString("Rule0008ToolTipPunctuationFormat", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), "Design", DiagnosticSeverity.Warning, true, (LocalizableString)new LocalizableResourceString("Rule0008ToolTipPunctuationDescription", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (string)null, Array.Empty<string>());
        public static readonly DiagnosticDescriptor Rule0009GlobalVarTriggerAndMethodPosition = new DiagnosticDescriptor(CustomALCodeCopAnalyzers.AnalyzerPrefix + "0009", (LocalizableString)new LocalizableResourceString("Rule0009GlobalVarTriggerAndMethodPositionTitle", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (LocalizableString)new LocalizableResourceString("Rule0009GlobalVarTriggerAndMethodPositionFormat", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), "Design", DiagnosticSeverity.Warning, true, (LocalizableString)new LocalizableResourceString("Rule0009GlobalVarTriggerAndMethodPositionDescription", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (string)null, Array.Empty<string>());
        public static readonly DiagnosticDescriptor Rule0010KeyNaming = new DiagnosticDescriptor(CustomALCodeCopAnalyzers.AnalyzerPrefix + "0010", (LocalizableString)new LocalizableResourceString("Rule0010KeyNamingTitle", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (LocalizableString)new LocalizableResourceString("Rule0010KeyNamingFormat", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), "Design", DiagnosticSeverity.Warning, true, (LocalizableString)new LocalizableResourceString("Rule0010KeyNamingDescription", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (string)null, Array.Empty<string>());
        public static readonly DiagnosticDescriptor Rule0011LabelPunctuation = new DiagnosticDescriptor(CustomALCodeCopAnalyzers.AnalyzerPrefix + "0011", (LocalizableString)new LocalizableResourceString("Rule0011LabelPunctuationTitle", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (LocalizableString)new LocalizableResourceString("Rule0011LabelPunctuationFormat", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), "Design", DiagnosticSeverity.Warning, true, (LocalizableString)new LocalizableResourceString("Rule0011LabelPunctuationDescription", CustomALCodeCopAnalyzers.ResourceManager, typeof(CustomALCodeCopAnalyzers)), (string)null, Array.Empty<string>());
    }
}
